from . import tutoring_topic
from . import tutoring_knowledge
from . import tutoring_student
from . import tutoring_session
from . import tutoring_homework
from . import tutoring_exam
# 知识库条目必须先在注册表里：练习册教材靠 _inherits 挂在它上面
from . import tutoring_library_item
from . import tutoring_workbook
from . import tutoring_workbook_file
from . import tutoring_workbook_page
from . import tutoring_workbook_goto
from . import tutoring_mistake_cause
from . import tutoring_mistake
from . import tutoring_mistake_ai
from . import tutoring_plot_ai
from . import tutoring_mistake_quickadd
from . import tutoring_time
from . import ir_ui_menu
from . import ir_ui_view
from . import res_partner
from . import res_users
from . import website
