from . import tutoring_topic
from . import tutoring_knowledge
from . import tutoring_student
from . import tutoring_session
from . import tutoring_homework
from . import tutoring_exam
from . import tutoring_workbook
from . import tutoring_workbook_file
from . import tutoring_workbook_goto
from . import tutoring_mistake
from . import tutoring_mistake_quickadd
from . import ir_ui_menu
from . import ir_ui_view
from . import res_partner
